services:
  postgres:
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"

  redis:
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

  backend:
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  worker:
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"

  frontend:
    build:
      target: prod
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"
