from datetime import UTC, datetime
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.integrations.github_api import InstallationClient
from app.models.pull_request import PullRequest
from app.models.repository import Repository
from app.models.review import Review, ReviewComment
from app.services.diff_fetcher import find_installation_for_repo

log = get_logger("basira.poster")

MAX_INLINE_COMMENTS = 20

SEVERITY_BADGE = {
    "critical": "[critical]",
    "major": "[major]",
    "minor": "[minor]",
    "nit": "[nit]",
}


class PosterError(Exception):
    pass


def _format_summary_markdown(review: Review, comments: list[ReviewComment]) -> str:
    counts = review.counts or {}
    header_lines = ["**basira review**", ""]
    if review.summary:
        header_lines.append(review.summary)
        header_lines.append("")

    breakdown_parts: list[str] = []
    for sev in ("critical", "major", "minor", "nit"):
        n = counts.get(sev, 0)
        if n:
            breakdown_parts.append(f"{sev}: {n}")
    if breakdown_parts:
        header_lines.append("Findings: " + ", ".join(breakdown_parts))

    inline_count = sum(1 for c in comments if c.line is not None)
    file_only = [c for c in comments if c.line is None]

    if inline_count:
        header_lines.append(f"Inline comments: {min(inline_count, MAX_INLINE_COMMENTS)}")
    if file_only:
        header_lines.append("")
        header_lines.append("File-level notes:")
        for c in file_only[:MAX_INLINE_COMMENTS]:
            badge = SEVERITY_BADGE.get(c.severity, "")
            header_lines.append(f"- {badge} `{c.path}` — {c.message}")

    header_lines.append("")
    header_lines.append("<sub>generated by basira</sub>")
    return "\n".join(header_lines)


def _build_inline_payload(c: ReviewComment) -> dict[str, Any]:
    body_parts = [SEVERITY_BADGE.get(c.severity, ""), c.message]
    if c.suggestion:
        body_parts.append("")
        body_parts.append("```suggestion")
        body_parts.append(c.suggestion)
        body_parts.append("```")
    return {
        "path": c.path,
        "line": c.line,
        "side": c.side or "RIGHT",
        "body": "\n".join(p for p in body_parts if p),
    }


async def _existing_basira_review_id(
    client: InstallationClient, owner: str, name: str, number: int
) -> int | None:
    """Find a prior review by this app to edit instead of posting a duplicate."""
    try:
        reviews = await client.list_reviews(owner, name, number)
    except Exception:
        return None
    for rv in reviews:
        body = rv.get("body") or ""
        if "basira review" in body.lower() and rv.get("state") in ("COMMENTED", "PENDING"):
            return int(rv["id"])
    return None


async def post_review_to_github(
    db: AsyncSession,
    review: Review,
    *,
    client_override: InstallationClient | None = None,
) -> dict[str, Any]:
    pr = await db.get(PullRequest, review.pull_request_id)
    repo = await db.get(Repository, review.repository_id)
    if pr is None or repo is None:
        raise PosterError("pull_request or repository missing")

    comments_stmt = select(ReviewComment).where(ReviewComment.review_id == review.id)
    comments = list((await db.execute(comments_stmt)).scalars().all())

    if client_override is not None:
        client = client_override
    else:
        inst = await find_installation_for_repo(db, repo.id)
        if inst is None:
            raise PosterError(f"no installation linked to {repo.full_name}")
        client = InstallationClient(inst.installation_id)

    inline_comments = [c for c in comments if c.line is not None][:MAX_INLINE_COMMENTS]
    inline_payload = [_build_inline_payload(c) for c in inline_comments]
    summary_body = _format_summary_markdown(review, comments)

    existing_id = await _existing_basira_review_id(client, repo.owner, repo.name, pr.number)

    if existing_id is not None and not inline_payload:
        # just refresh the summary
        result = await client.update_review_body(
            repo.owner, repo.name, pr.number, existing_id, summary_body
        )
    else:
        # GitHub does not support editing a review's inline comments via PATCH; we
        # post a fresh review and accept that a prior summary stays. Trade-off
        # noted in CLAUDE.md: editing comments on resync is a v0.2 problem.
        result = await client.create_review(
            repo.owner,
            repo.name,
            pr.number,
            commit_id=review.head_sha,
            body=summary_body,
            event="COMMENT",
            comments=inline_payload or None,
        )

    review.status = "posted"
    review.github_review_id = int(result.get("id", 0)) or review.github_review_id
    for c in inline_comments:
        c.posted = True
    if not inline_comments:
        for c in comments:
            c.posted = True

    await db.commit()
    await db.refresh(review)

    log.info(
        "poster.posted",
        repo=repo.full_name,
        pr=pr.number,
        inline=len(inline_payload),
        github_review_id=review.github_review_id,
    )
    return {
        "github_review_id": review.github_review_id,
        "inline_count": len(inline_payload),
        "posted_at": datetime.now(UTC).isoformat(),
    }
